name: E2E Tests - Native Demo App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  android:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run Android tests on BrowserStack
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          BROWSERSTACK_APP_ID_ANDROID: ${{ secrets.BROWSERSTACK_APP_ID_ANDROID }}
        run: npx wdio wdio.conf.js --capabilities 0  

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results-android
          path: allure-results/
          retention-days: 2  

  ios:
    name: iOS 
    runs-on: mac-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Run iOS tests on BrowserStack
        env:
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
          BROWSERSTACK_APP_ID_IOS: ${{ secrets.BROWSERSTACK_APP_ID_IOS }}
        run: npx wdio wdio.conf.js --capabilities 1   

      - name: Upload Allure results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: allure-results-ios
          path: allure-results/
          retention-days: 2

  report:
    name: Gerar Relatório Final HTML
    needs: [android, ios]           
    runs-on: ubuntu-latest
    if: always()                    
    steps:
      - name: Download todos os resultados
        uses: actions/download-artifact@v4
        with:
          path: all-results
          pattern: allure-results-*
          merge-multiple: true

      - name: Instalar Allure CLI
        run: npm install -g allure-commandline

      - name: Gerar relatório único
        run: |
          allure generate all-results --clean -o allure-report

      - name: Upload do relatório final HTML
        uses: actions/upload-artifact@v4
        with:
          name: Relatório Final HTML - Android + iOS
          path: allure-report
          retention-days: 30